blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/mr-ravi26/alpha-hunt/discussions
    about: Ask questions or discuss ideas that aren't a bug report or feature request.
